<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>LearnSite</AssemblyName>
    <RootNamespace>LearnSite</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../App_Code/**/*.cs" />
    <Reference Include="System.Web" />
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Drawing" /><Reference Include="System.Web.Extensions" /><Reference Include="System.Web.DataVisualization" /><Reference Include="System.Web.Services" /><Reference Include="System.DirectoryServices" />
  </ItemGroup>

  <ItemGroup>
    <!-- 使用通配符引用所有 Bin 目录中的 DLL -->
    <Reference Include="../Bin/*.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>

</Project>
