version: '3.8'

services:
  learnsite-web:
    build:
      context: .
    image: orzg/learnsite-web:latest
    environment:
      - DB_PASSWORD=${DB_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "8080:8080"
    volumes:
      - ./backupdb:/app/backupdb
    depends_on:
      - learnsite-db
    restart: always

  learnsite-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./backupdb:/app/backupdb
    restart: always

volumes:
  mssql-data:
