<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../App_Code/**/*.cs" />
    <Reference Include="System.Web" />
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>
